### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by dinohamzic** [solidusio/solidus_starter_frontend#76]
Now that we rewrote and decoupled the JavaScript codebase from the Solidus one (and jQuery), we should find a way to exclude jQuery from being included in the frontend.

**Comment by cloud69420** [comment]
No, please keep it! :)

It makes the code so much cleaner and easier-to-understand in my humble opinion, and the people who say jQuery is dead are usually the same people who say Rails is dead. 

Granted, jQuery did mess up by joining and supporting useless projects like jQuery UI and jQuery Mobile. I should know, I lost $30.000 when jQuery Mobile was abandoned and my app was left to rot :(

But the way I see it, we use jQuery for the same reason we use SCSS instead of CSS.

**Comment by fthobe** [comment]
@jarednorman I did not see any jquery in the starter frontend, can be closed righ?

**Comment by jarednorman** [comment]
Yeah, I don't see any jQuery either.
