### ISSUE TITLE
Remove the use of class names for JavaScript functionality

### ISSUE THREAD

**Issue by markmead** [solidusio/solidus_starter_frontend#82]
👋 Hey

I've been using this repo for a project recently and found the use of class names for JS functionality rather frustrating.

I kept deleting the class name, replacing it with my own classes and then having functionality not work. There are only a few cases, but I think it's worth looking at.

Keep logic to ID's and style to classes.

I can take a look at this if someone wants me too.

**Comment by kennyadsl** [comment]
I think it's a great idea! If you have time to submit a PR please go ahead.

**Comment by markmead** [comment]
Awesome! I'll start working on that over the weekend.

I'm thinking the use of `data` attributes might be easier to work with rather than IDs, thoughts? @kennyadsl 

Something like `data-js="delete-order-item"` for example.

**Comment by kennyadsl** [comment]
I'm ok using data-attributes for this, even if retrieving elements with data-attributes is slower than classes, which is slower than IDs. 

I'd rather not use `data-js` though, since the same attribute could have several meanings/triggers in JS. I'm not sure since I don't know the context in the example you reported but probably something like `data-js-delete-order-item` (without any value) is more flexible?

Let me say that I don't have a lot of experience with this specific topic so maybe it's better to look for some best practices before?

**Comment by markmead** [comment]
Currently, they are attached to a `data-module` attribute. This is something others are doing and what I was exposed to at GOVUK's Department of Education. It feels fairly efficient and familiar.

I'm not sure `data-js-delete-order-item` is where I'd take it, that feels uncontrolled. With `data-module="name-here"` the logic is scoped. As a developer, I'd quickly pickup that's where logic is kept.

I am open to switching though!

You can see the progress here - #84
